@startuml

actor Member as "Information Analyst in the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC35 as "Get population of a continents statistic."

    usecase UCa as "Output the report with 7 statistic."

    Member - UC35
    UC35 ..> UCa : include
    UC35 - Database
}

@enduml