@startuml

actor Member as "Member of the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC15 as "Get the Top N Populated Countries
    in a Continent where N is Provided by the User."

    usecase UCa as "Output the report."

    Member - UC15
    UC15 ..> UCa : include
    UC15 - Database
}

@enduml