@startuml

actor Member as "Information Analyst in the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC6 as "Get reports of people living in and out of cities for each Country."

    usecase UCa as "Output the report."

    Member - UC6
    UC6 ..> UCa : include
    UC6 - Database
}

@enduml