@startuml

actor Member as "Member of the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC24 as "Get all the cities in a
    continent organised by largest population to smallest."

    usecase UCa as "Output the report."

    Member - UC24
    UC24 ..> UCa : include
    UC24 - Database
}

@enduml