@startuml

actor Member as "Member of the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC23 as "Get the Top N Populated Cities
    in a Region where N is Provided by the User."

    usecase UCa as "Output the report."

    Member - UC23
    UC23 ..> UCa : include
    UC23 - Database
}

@enduml