@startuml

actor Member as "Member of the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC14 as "Get the Top N Populated Capital Cities
    in the World where N is Provided by the User."

    usecase UCa as "Output the report."

    Member - UC14
    UC14 ..> UCa : include
    UC14 - Database
}

@enduml