@startuml

actor Member as "Member of the
organisation"

rectangle Database

rectangle "Population Information System" {
    usecase UC25 as "Get the Top N Populated Cities
    in a continent where N is Provided by the User."

    usecase UCa as "Output the report."

    Member - UC25
    UC25 ..> UCa : include
    UC25 - Database
}

@enduml